// source: internal/proto_files/service/product_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var internal_proto_files_domain_product_pb = require('../../../internal/proto_files/domain/product_pb.js');
goog.object.extend(proto, internal_proto_files_domain_product_pb);
goog.exportSymbol('proto.product.internal.proto_files.service.AddProductRequest', null, global);
goog.exportSymbol('proto.product.internal.proto_files.service.AddProductResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.product.internal.proto_files.service.AddProductRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.product.internal.proto_files.service.AddProductRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.product.internal.proto_files.service.AddProductRequest.displayName = 'proto.product.internal.proto_files.service.AddProductRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.product.internal.proto_files.service.AddProductResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.product.internal.proto_files.service.AddProductResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.product.internal.proto_files.service.AddProductResponse.displayName = 'proto.product.internal.proto_files.service.AddProductResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.product.internal.proto_files.service.AddProductRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.product.internal.proto_files.service.AddProductRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.product.internal.proto_files.service.AddProductRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.service.AddProductRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    product: (f = msg.getProduct()) && internal_proto_files_domain_product_pb.Product.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.product.internal.proto_files.service.AddProductRequest}
 */
proto.product.internal.proto_files.service.AddProductRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.product.internal.proto_files.service.AddProductRequest;
  return proto.product.internal.proto_files.service.AddProductRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.product.internal.proto_files.service.AddProductRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.product.internal.proto_files.service.AddProductRequest}
 */
proto.product.internal.proto_files.service.AddProductRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new internal_proto_files_domain_product_pb.Product;
      reader.readMessage(value,internal_proto_files_domain_product_pb.Product.deserializeBinaryFromReader);
      msg.setProduct(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.product.internal.proto_files.service.AddProductRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.product.internal.proto_files.service.AddProductRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.product.internal.proto_files.service.AddProductRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.service.AddProductRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProduct();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      internal_proto_files_domain_product_pb.Product.serializeBinaryToWriter
    );
  }
};


/**
 * optional product.internal.proto_files.domain.Product product = 1;
 * @return {?proto.product.internal.proto_files.domain.Product}
 */
proto.product.internal.proto_files.service.AddProductRequest.prototype.getProduct = function() {
  return /** @type{?proto.product.internal.proto_files.domain.Product} */ (
    jspb.Message.getWrapperField(this, internal_proto_files_domain_product_pb.Product, 1));
};


/**
 * @param {?proto.product.internal.proto_files.domain.Product|undefined} value
 * @return {!proto.product.internal.proto_files.service.AddProductRequest} returns this
*/
proto.product.internal.proto_files.service.AddProductRequest.prototype.setProduct = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.product.internal.proto_files.service.AddProductRequest} returns this
 */
proto.product.internal.proto_files.service.AddProductRequest.prototype.clearProduct = function() {
  return this.setProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.product.internal.proto_files.service.AddProductRequest.prototype.hasProduct = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.product.internal.proto_files.service.AddProductResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.product.internal.proto_files.service.AddProductResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.product.internal.proto_files.service.AddProductResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.service.AddProductResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    createdProduct: (f = msg.getCreatedProduct()) && internal_proto_files_domain_product_pb.Product.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.product.internal.proto_files.service.AddProductResponse}
 */
proto.product.internal.proto_files.service.AddProductResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.product.internal.proto_files.service.AddProductResponse;
  return proto.product.internal.proto_files.service.AddProductResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.product.internal.proto_files.service.AddProductResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.product.internal.proto_files.service.AddProductResponse}
 */
proto.product.internal.proto_files.service.AddProductResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new internal_proto_files_domain_product_pb.Product;
      reader.readMessage(value,internal_proto_files_domain_product_pb.Product.deserializeBinaryFromReader);
      msg.setCreatedProduct(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.product.internal.proto_files.service.AddProductResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.product.internal.proto_files.service.AddProductResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.product.internal.proto_files.service.AddProductResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.service.AddProductResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCreatedProduct();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      internal_proto_files_domain_product_pb.Product.serializeBinaryToWriter
    );
  }
};


/**
 * optional product.internal.proto_files.domain.Product created_product = 1;
 * @return {?proto.product.internal.proto_files.domain.Product}
 */
proto.product.internal.proto_files.service.AddProductResponse.prototype.getCreatedProduct = function() {
  return /** @type{?proto.product.internal.proto_files.domain.Product} */ (
    jspb.Message.getWrapperField(this, internal_proto_files_domain_product_pb.Product, 1));
};


/**
 * @param {?proto.product.internal.proto_files.domain.Product|undefined} value
 * @return {!proto.product.internal.proto_files.service.AddProductResponse} returns this
*/
proto.product.internal.proto_files.service.AddProductResponse.prototype.setCreatedProduct = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.product.internal.proto_files.service.AddProductResponse} returns this
 */
proto.product.internal.proto_files.service.AddProductResponse.prototype.clearCreatedProduct = function() {
  return this.setCreatedProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.product.internal.proto_files.service.AddProductResponse.prototype.hasCreatedProduct = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.product.internal.proto_files.service);
