// source: internal/proto_files/domain/product.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.product.internal.proto_files.domain.AddProductRequest', null, global);
goog.exportSymbol('proto.product.internal.proto_files.domain.AddProductResponse', null, global);
goog.exportSymbol('proto.product.internal.proto_files.domain.Product', null, global);
goog.exportSymbol('proto.product.internal.proto_files.domain.Timestamp', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.product.internal.proto_files.domain.Product = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.product.internal.proto_files.domain.Product, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.product.internal.proto_files.domain.Product.displayName = 'proto.product.internal.proto_files.domain.Product';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.product.internal.proto_files.domain.Timestamp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.product.internal.proto_files.domain.Timestamp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.product.internal.proto_files.domain.Timestamp.displayName = 'proto.product.internal.proto_files.domain.Timestamp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.product.internal.proto_files.domain.AddProductRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.product.internal.proto_files.domain.AddProductRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.product.internal.proto_files.domain.AddProductRequest.displayName = 'proto.product.internal.proto_files.domain.AddProductRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.product.internal.proto_files.domain.AddProductResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.product.internal.proto_files.domain.AddProductResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.product.internal.proto_files.domain.AddProductResponse.displayName = 'proto.product.internal.proto_files.domain.AddProductResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.product.internal.proto_files.domain.Product.prototype.toObject = function(opt_includeInstance) {
  return proto.product.internal.proto_files.domain.Product.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.product.internal.proto_files.domain.Product} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.domain.Product.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    price: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    slug: jspb.Message.getFieldWithDefault(msg, 5, ""),
    inactive: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    quantity: jspb.Message.getFieldWithDefault(msg, 7, 0),
    createdAt: (f = msg.getCreatedAt()) && proto.product.internal.proto_files.domain.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && proto.product.internal.proto_files.domain.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && proto.product.internal.proto_files.domain.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.product.internal.proto_files.domain.Product}
 */
proto.product.internal.proto_files.domain.Product.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.product.internal.proto_files.domain.Product;
  return proto.product.internal.proto_files.domain.Product.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.product.internal.proto_files.domain.Product} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.product.internal.proto_files.domain.Product}
 */
proto.product.internal.proto_files.domain.Product.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPrice(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSlug(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInactive(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setQuantity(value);
      break;
    case 8:
      var value = new proto.product.internal.proto_files.domain.Timestamp;
      reader.readMessage(value,proto.product.internal.proto_files.domain.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 9:
      var value = new proto.product.internal.proto_files.domain.Timestamp;
      reader.readMessage(value,proto.product.internal.proto_files.domain.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 10:
      var value = new proto.product.internal.proto_files.domain.Timestamp;
      reader.readMessage(value,proto.product.internal.proto_files.domain.Timestamp.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.product.internal.proto_files.domain.Product.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.product.internal.proto_files.domain.Product.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.product.internal.proto_files.domain.Product} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.domain.Product.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getSlug();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getInactive();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.product.internal.proto_files.domain.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.product.internal.proto_files.domain.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.product.internal.proto_files.domain.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.product.internal.proto_files.domain.Product.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
 */
proto.product.internal.proto_files.domain.Product.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.product.internal.proto_files.domain.Product.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
 */
proto.product.internal.proto_files.domain.Product.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.product.internal.proto_files.domain.Product.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
 */
proto.product.internal.proto_files.domain.Product.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional double price = 4;
 * @return {number}
 */
proto.product.internal.proto_files.domain.Product.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
 */
proto.product.internal.proto_files.domain.Product.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional string slug = 5;
 * @return {string}
 */
proto.product.internal.proto_files.domain.Product.prototype.getSlug = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
 */
proto.product.internal.proto_files.domain.Product.prototype.setSlug = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bool inactive = 6;
 * @return {boolean}
 */
proto.product.internal.proto_files.domain.Product.prototype.getInactive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
 */
proto.product.internal.proto_files.domain.Product.prototype.setInactive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional uint64 quantity = 7;
 * @return {number}
 */
proto.product.internal.proto_files.domain.Product.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
 */
proto.product.internal.proto_files.domain.Product.prototype.setQuantity = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional Timestamp created_at = 8;
 * @return {?proto.product.internal.proto_files.domain.Timestamp}
 */
proto.product.internal.proto_files.domain.Product.prototype.getCreatedAt = function() {
  return /** @type{?proto.product.internal.proto_files.domain.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.product.internal.proto_files.domain.Timestamp, 8));
};


/**
 * @param {?proto.product.internal.proto_files.domain.Timestamp|undefined} value
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
*/
proto.product.internal.proto_files.domain.Product.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
 */
proto.product.internal.proto_files.domain.Product.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.product.internal.proto_files.domain.Product.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional Timestamp updated_at = 9;
 * @return {?proto.product.internal.proto_files.domain.Timestamp}
 */
proto.product.internal.proto_files.domain.Product.prototype.getUpdatedAt = function() {
  return /** @type{?proto.product.internal.proto_files.domain.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.product.internal.proto_files.domain.Timestamp, 9));
};


/**
 * @param {?proto.product.internal.proto_files.domain.Timestamp|undefined} value
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
*/
proto.product.internal.proto_files.domain.Product.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
 */
proto.product.internal.proto_files.domain.Product.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.product.internal.proto_files.domain.Product.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional Timestamp deleted_at = 10;
 * @return {?proto.product.internal.proto_files.domain.Timestamp}
 */
proto.product.internal.proto_files.domain.Product.prototype.getDeletedAt = function() {
  return /** @type{?proto.product.internal.proto_files.domain.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.product.internal.proto_files.domain.Timestamp, 10));
};


/**
 * @param {?proto.product.internal.proto_files.domain.Timestamp|undefined} value
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
*/
proto.product.internal.proto_files.domain.Product.prototype.setDeletedAt = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.product.internal.proto_files.domain.Product} returns this
 */
proto.product.internal.proto_files.domain.Product.prototype.clearDeletedAt = function() {
  return this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.product.internal.proto_files.domain.Product.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 10) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.product.internal.proto_files.domain.Timestamp.prototype.toObject = function(opt_includeInstance) {
  return proto.product.internal.proto_files.domain.Timestamp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.product.internal.proto_files.domain.Timestamp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.domain.Timestamp.toObject = function(includeInstance, msg) {
  var f, obj = {
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.product.internal.proto_files.domain.Timestamp}
 */
proto.product.internal.proto_files.domain.Timestamp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.product.internal.proto_files.domain.Timestamp;
  return proto.product.internal.proto_files.domain.Timestamp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.product.internal.proto_files.domain.Timestamp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.product.internal.proto_files.domain.Timestamp}
 */
proto.product.internal.proto_files.domain.Timestamp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.product.internal.proto_files.domain.Timestamp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.product.internal.proto_files.domain.Timestamp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.product.internal.proto_files.domain.Timestamp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.domain.Timestamp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp timestamp = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.product.internal.proto_files.domain.Timestamp.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.product.internal.proto_files.domain.Timestamp} returns this
*/
proto.product.internal.proto_files.domain.Timestamp.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.product.internal.proto_files.domain.Timestamp} returns this
 */
proto.product.internal.proto_files.domain.Timestamp.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.product.internal.proto_files.domain.Timestamp.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.product.internal.proto_files.domain.AddProductRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.product.internal.proto_files.domain.AddProductRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.product.internal.proto_files.domain.AddProductRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.domain.AddProductRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    product: (f = msg.getProduct()) && proto.product.internal.proto_files.domain.Product.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.product.internal.proto_files.domain.AddProductRequest}
 */
proto.product.internal.proto_files.domain.AddProductRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.product.internal.proto_files.domain.AddProductRequest;
  return proto.product.internal.proto_files.domain.AddProductRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.product.internal.proto_files.domain.AddProductRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.product.internal.proto_files.domain.AddProductRequest}
 */
proto.product.internal.proto_files.domain.AddProductRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.product.internal.proto_files.domain.Product;
      reader.readMessage(value,proto.product.internal.proto_files.domain.Product.deserializeBinaryFromReader);
      msg.setProduct(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.product.internal.proto_files.domain.AddProductRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.product.internal.proto_files.domain.AddProductRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.product.internal.proto_files.domain.AddProductRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.domain.AddProductRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProduct();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.product.internal.proto_files.domain.Product.serializeBinaryToWriter
    );
  }
};


/**
 * optional Product product = 1;
 * @return {?proto.product.internal.proto_files.domain.Product}
 */
proto.product.internal.proto_files.domain.AddProductRequest.prototype.getProduct = function() {
  return /** @type{?proto.product.internal.proto_files.domain.Product} */ (
    jspb.Message.getWrapperField(this, proto.product.internal.proto_files.domain.Product, 1));
};


/**
 * @param {?proto.product.internal.proto_files.domain.Product|undefined} value
 * @return {!proto.product.internal.proto_files.domain.AddProductRequest} returns this
*/
proto.product.internal.proto_files.domain.AddProductRequest.prototype.setProduct = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.product.internal.proto_files.domain.AddProductRequest} returns this
 */
proto.product.internal.proto_files.domain.AddProductRequest.prototype.clearProduct = function() {
  return this.setProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.product.internal.proto_files.domain.AddProductRequest.prototype.hasProduct = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.product.internal.proto_files.domain.AddProductResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.product.internal.proto_files.domain.AddProductResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.product.internal.proto_files.domain.AddProductResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.domain.AddProductResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    createdProduct: (f = msg.getCreatedProduct()) && proto.product.internal.proto_files.domain.Product.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.product.internal.proto_files.domain.AddProductResponse}
 */
proto.product.internal.proto_files.domain.AddProductResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.product.internal.proto_files.domain.AddProductResponse;
  return proto.product.internal.proto_files.domain.AddProductResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.product.internal.proto_files.domain.AddProductResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.product.internal.proto_files.domain.AddProductResponse}
 */
proto.product.internal.proto_files.domain.AddProductResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.product.internal.proto_files.domain.Product;
      reader.readMessage(value,proto.product.internal.proto_files.domain.Product.deserializeBinaryFromReader);
      msg.setCreatedProduct(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.product.internal.proto_files.domain.AddProductResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.product.internal.proto_files.domain.AddProductResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.product.internal.proto_files.domain.AddProductResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.product.internal.proto_files.domain.AddProductResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCreatedProduct();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.product.internal.proto_files.domain.Product.serializeBinaryToWriter
    );
  }
};


/**
 * optional Product created_product = 1;
 * @return {?proto.product.internal.proto_files.domain.Product}
 */
proto.product.internal.proto_files.domain.AddProductResponse.prototype.getCreatedProduct = function() {
  return /** @type{?proto.product.internal.proto_files.domain.Product} */ (
    jspb.Message.getWrapperField(this, proto.product.internal.proto_files.domain.Product, 1));
};


/**
 * @param {?proto.product.internal.proto_files.domain.Product|undefined} value
 * @return {!proto.product.internal.proto_files.domain.AddProductResponse} returns this
*/
proto.product.internal.proto_files.domain.AddProductResponse.prototype.setCreatedProduct = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.product.internal.proto_files.domain.AddProductResponse} returns this
 */
proto.product.internal.proto_files.domain.AddProductResponse.prototype.clearCreatedProduct = function() {
  return this.setCreatedProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.product.internal.proto_files.domain.AddProductResponse.prototype.hasCreatedProduct = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.product.internal.proto_files.domain);
