// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto_files/domain/product.proto

// TODO: add protobuf linter and dependency manager, change the Product message field
// ref: https://medium.com/stackpulse/grpc-in-practice-directory-structure-linting-and-more-d4d438ac4f86

package domain

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	// @inject_tag: gorm:"primary_key"
	Id          uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Slug        string  `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Inactive    bool    `protobuf:"varint,6,opt,name=inactive,proto3" json:"inactive,omitempty"`
	Quantity    uint64  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// @inject_tag: gorm:"type:timestamp"
	CreatedAt *Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"type:timestamp"`
	// @inject_tag: gorm:"type:timestamp"
	UpdatedAt *Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"type:timestamp"`
	// @inject_tag: gorm:"type:timestamp"
	DeletedAt            *Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty" gorm:"type:timestamp"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_0780fec618c73939, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Product) GetInactive() bool {
	if m != nil {
		return m.Inactive
	}
	return false
}

func (m *Product) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetCreatedAt() *Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Product) GetUpdatedAt() *Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Product) GetDeletedAt() *Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Timestamp struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0780fec618c73939, []int{1}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// AddClient Request and Response
type AddProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductRequest) Reset()         { *m = AddProductRequest{} }
func (m *AddProductRequest) String() string { return proto.CompactTextString(m) }
func (*AddProductRequest) ProtoMessage()    {}
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0780fec618c73939, []int{2}
}

func (m *AddProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductRequest.Unmarshal(m, b)
}
func (m *AddProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductRequest.Marshal(b, m, deterministic)
}
func (m *AddProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductRequest.Merge(m, src)
}
func (m *AddProductRequest) XXX_Size() int {
	return xxx_messageInfo_AddProductRequest.Size(m)
}
func (m *AddProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductRequest proto.InternalMessageInfo

func (m *AddProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type AddProductResponse struct {
	CreatedProduct       *Product `protobuf:"bytes,1,opt,name=created_product,json=createdProduct,proto3" json:"created_product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductResponse) Reset()         { *m = AddProductResponse{} }
func (m *AddProductResponse) String() string { return proto.CompactTextString(m) }
func (*AddProductResponse) ProtoMessage()    {}
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0780fec618c73939, []int{3}
}

func (m *AddProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductResponse.Unmarshal(m, b)
}
func (m *AddProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductResponse.Marshal(b, m, deterministic)
}
func (m *AddProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductResponse.Merge(m, src)
}
func (m *AddProductResponse) XXX_Size() int {
	return xxx_messageInfo_AddProductResponse.Size(m)
}
func (m *AddProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductResponse proto.InternalMessageInfo

func (m *AddProductResponse) GetCreatedProduct() *Product {
	if m != nil {
		return m.CreatedProduct
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "product.internal.proto_files.domain.Product")
	proto.RegisterType((*Timestamp)(nil), "product.internal.proto_files.domain.Timestamp")
	proto.RegisterType((*AddProductRequest)(nil), "product.internal.proto_files.domain.AddProductRequest")
	proto.RegisterType((*AddProductResponse)(nil), "product.internal.proto_files.domain.AddProductResponse")
}

func init() {
	proto.RegisterFile("internal/proto_files/domain/product.proto", fileDescriptor_0780fec618c73939)
}

var fileDescriptor_0780fec618c73939 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x5f, 0xab, 0xd3, 0x30,
	0x18, 0xc6, 0xc9, 0xce, 0xce, 0xd9, 0xfa, 0x0e, 0x26, 0x86, 0x83, 0x84, 0xde, 0x58, 0xea, 0x4d,
	0x05, 0xc9, 0x60, 0x82, 0x7a, 0x3b, 0x41, 0xef, 0x04, 0xa9, 0x7a, 0xa3, 0x17, 0x23, 0x6b, 0xde,
	0x95, 0x60, 0x9b, 0x76, 0x6d, 0x3a, 0xf0, 0xc2, 0xcf, 0xe0, 0x37, 0xf0, 0xb3, 0x4a, 0x9b, 0xa4,
	0x16, 0xbc, 0x99, 0x3b, 0x77, 0xef, 0x9f, 0x3c, 0xbf, 0xbc, 0xc9, 0x93, 0xc0, 0x73, 0xa5, 0x0d,
	0x36, 0x5a, 0x14, 0x9b, 0xba, 0xa9, 0x4c, 0xb5, 0x3f, 0xaa, 0x02, 0xdb, 0x8d, 0xac, 0x4a, 0xa1,
	0x74, 0x5f, 0x92, 0x5d, 0x66, 0xf8, 0xd0, 0xa2, 0xcf, 0x7c, 0xea, 0x25, 0x7c, 0x22, 0xe1, 0x56,
	0x12, 0x3e, 0xcd, 0xab, 0x2a, 0x2f, 0xd0, 0xd2, 0x0e, 0xdd, 0x71, 0x63, 0x54, 0x89, 0xad, 0x11,
	0x65, 0x6d, 0x57, 0xc7, 0xbf, 0x6f, 0x60, 0xf1, 0xd1, 0x82, 0xe8, 0x1a, 0x66, 0x4a, 0x32, 0x12,
	0x91, 0x64, 0x9e, 0xce, 0x94, 0xa4, 0x14, 0xe6, 0x5a, 0x94, 0xc8, 0x66, 0x11, 0x49, 0x82, 0x74,
	0x88, 0x69, 0x04, 0x2b, 0x89, 0x6d, 0xd6, 0xa8, 0xda, 0xa8, 0x4a, 0xb3, 0x9b, 0xa1, 0x35, 0x2d,
	0xd1, 0x7b, 0xb8, 0xad, 0x1b, 0x95, 0x21, 0x9b, 0x47, 0x24, 0x21, 0xa9, 0x4d, 0x7a, 0x56, 0x5b,
	0x74, 0x39, 0xbb, 0xb5, 0xac, 0x3e, 0xa6, 0x21, 0x2c, 0x95, 0x16, 0x99, 0x51, 0x67, 0x64, 0x77,
	0x11, 0x49, 0x96, 0xe9, 0x98, 0xf7, 0xbd, 0x53, 0x27, 0xb4, 0x51, 0xe6, 0x07, 0x5b, 0x0c, 0x13,
	0x8d, 0x39, 0xfd, 0x00, 0x90, 0x35, 0x28, 0x0c, 0xca, 0xbd, 0x30, 0x6c, 0x19, 0x91, 0x64, 0xb5,
	0xe5, 0xfc, 0x82, 0xeb, 0xe0, 0x9f, 0xfd, 0xe9, 0xd3, 0xc0, 0x11, 0x76, 0xa6, 0xc7, 0x75, 0xb5,
	0xf4, 0xb8, 0xe0, 0x3a, 0x9c, 0x23, 0x58, 0x9c, 0xc4, 0x02, 0x1d, 0x0e, 0xae, 0xc3, 0x39, 0xc2,
	0xce, 0xc4, 0xef, 0x20, 0x18, 0xeb, 0xf4, 0x0d, 0x04, 0xa3, 0x81, 0x83, 0x51, 0xab, 0x6d, 0xc8,
	0xad, 0xc5, 0xdc, 0x5b, 0x3c, 0xc5, 0x8c, 0x8b, 0xe3, 0x6f, 0xf0, 0x78, 0x27, 0xa5, 0x73, 0x3a,
	0xc5, 0x53, 0x87, 0xad, 0xa1, 0xef, 0x61, 0xe1, 0xe6, 0x72, 0xb0, 0x17, 0x17, 0xcd, 0xe9, 0x29,
	0x5e, 0x1c, 0x7f, 0x07, 0x3a, 0x85, 0xb7, 0x75, 0xa5, 0x5b, 0xa4, 0x5f, 0xe0, 0x91, 0xb7, 0xe9,
	0x21, 0xbb, 0xac, 0x1d, 0xc4, 0xe5, 0xdb, 0x5f, 0x04, 0xd6, 0x2e, 0xfe, 0x84, 0xcd, 0xb9, 0x7f,
	0x5c, 0x3f, 0x01, 0xfe, 0xee, 0x4f, 0x5f, 0x5d, 0x84, 0xff, 0xe7, 0x36, 0xc2, 0xd7, 0xff, 0xad,
	0xb3, 0x07, 0x7d, 0xfb, 0xe4, 0xeb, 0xfd, 0xf8, 0x6d, 0xf3, 0xa6, 0xce, 0xdc, 0x7f, 0x3d, 0xdc,
	0x0d, 0xf2, 0x97, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x19, 0x06, 0x61, 0x55, 0xd5, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, "/product.internal.proto_files.domain.ProductService/AddProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) AddProduct(ctx context.Context, req *AddProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.internal.proto_files.domain.ProductService/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).AddProduct(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.internal.proto_files.domain.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProduct",
			Handler:    _ProductService_AddProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto_files/domain/product.proto",
}
