// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto_files/domain/product.proto

// TODO: add protobuf linter and dependency manager, change the Product message field
// ref: https://medium.com/stackpulse/grpc-in-practice-directory-structure-linting-and-more-d4d438ac4f86

package domain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	// @inject_tag: gorm:"primary_key"
	Id          uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Slug        string  `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	InActive    bool    `protobuf:"varint,6,opt,name=in_active,json=inActive,proto3" json:"in_active,omitempty"`
	OutOfStock  bool    `protobuf:"varint,7,opt,name=out_of_stock,json=outOfStock,proto3" json:"out_of_stock,omitempty"`
	// @inject_tag: gorm:"type:timestamp"
	CreatedAt *Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// @inject_tag: gorm:"type:timestamp"
	UpdatedAt *Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// @inject_tag: gorm:"type:timestamp"
	DeletedAt            *Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_0780fec618c73939, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Product) GetInActive() bool {
	if m != nil {
		return m.InActive
	}
	return false
}

func (m *Product) GetOutOfStock() bool {
	if m != nil {
		return m.OutOfStock
	}
	return false
}

func (m *Product) GetCreatedAt() *Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Product) GetUpdatedAt() *Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Product) GetDeletedAt() *Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Timestamp struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0780fec618c73939, []int{1}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "product.internal.proto_files.domain.Product")
	proto.RegisterType((*Timestamp)(nil), "product.internal.proto_files.domain.Timestamp")
}

func init() {
	proto.RegisterFile("internal/proto_files/domain/product.proto", fileDescriptor_0780fec618c73939)
}

var fileDescriptor_0780fec618c73939 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0xfe, 0xcf, 0x15, 0x31, 0x58, 0x15, 0xb2, 0xca, 0x40, 0x54, 0x96, 0xb0, 0xb8,
	0x52, 0x59, 0x58, 0x8b, 0xc4, 0x88, 0x40, 0x81, 0x89, 0x25, 0x72, 0x6d, 0x27, 0xb2, 0x48, 0xec,
	0x28, 0xb9, 0xf0, 0x8d, 0xf8, 0x9e, 0x28, 0x76, 0x12, 0x75, 0x44, 0xdd, 0xee, 0xde, 0xdd, 0xfb,
	0x0d, 0xf7, 0x0e, 0x1e, 0xb4, 0x41, 0x55, 0x1b, 0x5e, 0xec, 0xab, 0xda, 0xa2, 0x4d, 0x33, 0x5d,
	0xa8, 0x66, 0x2f, 0x6d, 0xc9, 0xb5, 0xe9, 0x24, 0xd9, 0x0a, 0x64, 0x6e, 0x44, 0xee, 0x87, 0x76,
	0xb0, 0xb0, 0x33, 0x0b, 0xf3, 0x96, 0xed, 0x5d, 0x6e, 0x6d, 0x5e, 0x28, 0x4f, 0x3b, 0xb5, 0xd9,
	0x1e, 0x75, 0xa9, 0x1a, 0xe4, 0x65, 0xe5, 0xb7, 0x77, 0xbf, 0x53, 0x58, 0xbe, 0x7b, 0x10, 0xb9,
	0x86, 0x89, 0x96, 0x34, 0x88, 0x82, 0x78, 0x96, 0x4c, 0xb4, 0x24, 0x04, 0x66, 0x86, 0x97, 0x8a,
	0x4e, 0xa2, 0x20, 0x0e, 0x13, 0x57, 0x93, 0x08, 0xd6, 0x52, 0x35, 0xa2, 0xd6, 0x15, 0x6a, 0x6b,
	0xe8, 0xd4, 0x8d, 0xce, 0x25, 0xb2, 0x81, 0x79, 0x55, 0x6b, 0xa1, 0xe8, 0x2c, 0x0a, 0xe2, 0x20,
	0xf1, 0x4d, 0xc7, 0x6a, 0x8a, 0x36, 0xa7, 0x73, 0xcf, 0xea, 0x6a, 0x72, 0x0b, 0xa1, 0x36, 0x29,
	0x17, 0xa8, 0x7f, 0x14, 0x5d, 0x44, 0x41, 0xbc, 0x4a, 0x56, 0xda, 0x1c, 0x5d, 0x4f, 0x22, 0xb8,
	0xb2, 0x2d, 0xa6, 0x36, 0x4b, 0x1b, 0xb4, 0xe2, 0x9b, 0x2e, 0xdd, 0x1c, 0x6c, 0x8b, 0x6f, 0xd9,
	0x47, 0xa7, 0x90, 0x57, 0x00, 0x51, 0x2b, 0x8e, 0x4a, 0xa6, 0x1c, 0xe9, 0x2a, 0x0a, 0xe2, 0xf5,
	0x81, 0xb1, 0x7f, 0x5c, 0x85, 0x7d, 0x0e, 0x47, 0x48, 0xc2, 0x9e, 0x70, 0xc4, 0x0e, 0xd7, 0x56,
	0x72, 0xc0, 0x85, 0x97, 0xe1, 0x7a, 0x82, 0xc7, 0x49, 0x55, 0xa8, 0x1e, 0x07, 0x97, 0xe1, 0x7a,
	0xc2, 0x11, 0x77, 0x2f, 0x10, 0x8e, 0x3a, 0x79, 0x82, 0x70, 0xcc, 0xd1, 0xe5, 0xb5, 0x3e, 0x6c,
	0x99, 0x4f, 0x9a, 0x0d, 0x49, 0x9f, 0x63, 0xc6, 0xe5, 0xe7, 0x9b, 0xaf, 0xcd, 0xf8, 0x61, 0x79,
	0x5d, 0x89, 0xfe, 0xb5, 0x4e, 0x0b, 0x67, 0x7b, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xc9,
	0x02, 0x8c, 0x80, 0x02, 0x00, 0x00,
}
