// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "productservice/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: _a0
func (_m *ProductRepository) CreateProduct(_a0 *domain.Product) (*domain.Product, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Product
	if rf, ok := ret.Get(0).(func(*domain.Product) *domain.Product); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	r0 = _a0

	return r0, nil
}
