// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto_files/service/product_service.proto

package domain_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AddClient Request and Response
type AddProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductRequest) Reset()         { *m = AddProductRequest{} }
func (m *AddProductRequest) String() string { return proto.CompactTextString(m) }
func (*AddProductRequest) ProtoMessage()    {}
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c59e542e8c9b251b, []int{0}
}

func (m *AddProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductRequest.Unmarshal(m, b)
}
func (m *AddProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductRequest.Marshal(b, m, deterministic)
}
func (m *AddProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductRequest.Merge(m, src)
}
func (m *AddProductRequest) XXX_Size() int {
	return xxx_messageInfo_AddProductRequest.Size(m)
}
func (m *AddProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductRequest proto.InternalMessageInfo

func (m *AddProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type AddProductResponse struct {
	CreatedProduct       *Product `protobuf:"bytes,1,opt,name=created_product,json=createdProduct,proto3" json:"created_product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductResponse) Reset()         { *m = AddProductResponse{} }
func (m *AddProductResponse) String() string { return proto.CompactTextString(m) }
func (*AddProductResponse) ProtoMessage()    {}
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c59e542e8c9b251b, []int{1}
}

func (m *AddProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductResponse.Unmarshal(m, b)
}
func (m *AddProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductResponse.Marshal(b, m, deterministic)
}
func (m *AddProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductResponse.Merge(m, src)
}
func (m *AddProductResponse) XXX_Size() int {
	return xxx_messageInfo_AddProductResponse.Size(m)
}
func (m *AddProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductResponse proto.InternalMessageInfo

func (m *AddProductResponse) GetCreatedProduct() *Product {
	if m != nil {
		return m.CreatedProduct
	}
	return nil
}

func init() {
	proto.RegisterType((*AddProductRequest)(nil), "product.internal.proto_files.service.AddProductRequest")
	proto.RegisterType((*AddProductResponse)(nil), "product.internal.proto_files.service.AddProductResponse")
}

func init() {
	proto.RegisterFile("internal/proto_files/service/product_service.proto", fileDescriptor_c59e542e8c9b251b)
}

var fileDescriptor_c59e542e8c9b251b = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xca, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x8f, 0x4f, 0xcb, 0xcc, 0x49, 0x2d,
	0xd6, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x05, 0x89, 0xa5, 0x94, 0x26, 0x97, 0xc4, 0x43,
	0xf9, 0x7a, 0x60, 0x35, 0x42, 0x2a, 0x50, 0x61, 0x3d, 0x98, 0x5e, 0x3d, 0x24, 0xbd, 0x7a, 0x50,
	0xb5, 0x52, 0x9a, 0x58, 0x4d, 0x4e, 0xc9, 0xcf, 0x4d, 0xcc, 0xcc, 0x83, 0x19, 0x0c, 0xd1, 0xa8,
	0x14, 0xcd, 0x25, 0xe8, 0x98, 0x92, 0x12, 0x00, 0x11, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x72, 0xe3, 0x62, 0x87, 0xaa, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0xd2, 0xd1, 0xc3,
	0x6b, 0x2f, 0xc4, 0x64, 0x3d, 0x98, 0x29, 0x30, 0xcd, 0x4a, 0xd9, 0x5c, 0x42, 0xc8, 0x86, 0x17,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x85, 0x72, 0xf1, 0x27, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0xa6,
	0xc4, 0x53, 0x62, 0x0b, 0x1f, 0xd4, 0x10, 0x28, 0xdf, 0x68, 0x22, 0x23, 0x17, 0x1f, 0x94, 0x1d,
	0x0c, 0x09, 0x07, 0xa1, 0x7a, 0x2e, 0x2e, 0x84, 0xfd, 0x42, 0xe6, 0x7a, 0xc4, 0x04, 0x9e, 0x1e,
	0x46, 0x70, 0x48, 0x59, 0x90, 0xae, 0x11, 0xe2, 0x55, 0x27, 0xb9, 0x28, 0x19, 0x78, 0x54, 0xa4,
	0x17, 0x15, 0x24, 0x43, 0xe3, 0x00, 0x16, 0xa9, 0x49, 0x6c, 0x60, 0x73, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x18, 0x1e, 0x55, 0xb1, 0x0b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, "/product.internal.proto_files.service.ProductService/AddProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) AddProduct(ctx context.Context, req *AddProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.internal.proto_files.service.ProductService/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).AddProduct(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.internal.proto_files.service.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProduct",
			Handler:    _ProductService_AddProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto_files/service/product_service.proto",
}
